name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Windows
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
